### ISSUE TITLE
nomp: ./install.sh : unbound variable

### ISSUE THREAD

**Issue by Redene** [m1dnight/vrm-pool#1]
All work until i start nomp install.sh
This is what he show me:
https://prnt.sc/iaq3hm

-Ubuntu 16.04 LTS from google cloud 2vcpu + 7.5go ram

**Comment by m1dnight** [comment]
This normal. The nomp script expects the root database password as an argument. 

When you have installed the mysql server using the script, you should have a file on your server located at `/root/mysql_password.txt`. (Generated here in the script: https://github.com/m1dnight/vrm-pool/blob/master/scripts/mysql/install.sh#L14-L16).

So if your root password is `foobar`, you would execute the nomp script as follows.

```
./install.sh foobar
```

Hope this helps.

**Comment by Redene** [comment]
Thanks, perfect 👍
